version: 2
updates:
  # Maintain Rust Crates
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "area/backend"
      - "kind/chore"

  # Maintain VS Code NPM Packages
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "area/extension"
      - "kind/chore"
    # Ignore VS Code engine updates (manual only)
    ignore:
      - dependency-name: "vscode"
